### PR TITLE
Cleanup Various Bugs

### LINKED ISSUE #363: Missing Texture in version 0.21.4
Electron source:
electron source

### PR DESCRIPTION
**Pull request by DStrand1**
I fixed a number of bugs from the Discord bugs channel pings. Each bullet point has its own commit, and they are listed here in commit order (aside from the texture additions commit, which is in between near the end).

- Fix positive Krypton loop from Krypton Difluoride
- Fix Distinct Buses mode sometimes not being saved on world reload
- Fix Disodium Phosphate translation, previously was "Sodium Diphosphate"
- ~~Fix Dimethylformamide cracking recipe being unbalanced~~
- Add "SMD" to Supra-Causal SMD translated names
- Fix typo in Wet Ethylene's translated name
- Convert our newly added fluids to translate the input RGB to opaque RGBA
- Fix Zerkelite Composition, included too little oxygen
- Fix Central Monitor lang translation requiring parameters when it shouldn't
- Fix Filtered Output Hatch voiding filters when block is broken
- Add circuit tier tooltips to Supra-Causal circuits
- Remove recipes for Unfired Clay Brick since the item was hidden. The recipes could still be seen through "U" on Clay in JEI
- Fix some typos in `GAConfig`
- Add OreDict entry to Hot Iron Ingot, `ingotHotIron`, and to Pyrolytic Carbon, `ingotPyroliticCarbon`. The second is matching NuclearCraft's ore dict entry for that material now
- Fix Empty Battery Hull tooltips being inconsistent with GTCE's
- Fix Implosion Compressor not using new explosives as a property, causing multiple explosives in recipes and breaking Electric Implosion Compressor recipe generation

Lastly, I added all of the textures from issue #363, and I am opening a new issue to enumerate the remaining textures we need to add since that one is very old now. I also removed a few unused MetaItems, some of which were not in game, but some that were. The ones in game that I removed:
- Rig Drill
- Well Connector Pipe
- Well Pipe
- Dust Field Shape

These were all marked for removal already according to #363, so I think it has been long enough that we can safely remove these.

Closes #363

### CODE REVIEW

File: src/main/java/gregicadditions/GAMaterials.java [hunk 1]
```diff
@@ -277,7 +277,7 @@
...
     public static final DustMaterial CircuitCompoundMK3 = new DustMaterial(907, "circuit_compound_mkc", 0x003316, MaterialIconSet.SAND, 2, of(new MaterialStack(IndiumGalliumPhosphide, 1), new MaterialStack(Dibismusthydroborat, 3), new MaterialStack(BismuthTellurite, 2)), 0);
     public static final DustMaterial YttriumOxide = new DustMaterial(906, "yttrium_oxide", 0xC6EBB3, MaterialIconSet.SAND, 2, of(new MaterialStack(Yttrium, 2), new MaterialStack(Oxygen, 3)), 0);
-    public static final DustMaterial Zirkelite = new DustMaterial(904, "zirkelite", 0x6B5E6A, MaterialIconSet.DULL, 4, of(new MaterialStack(Calcium, 2), new MaterialStack(Thorium, 2), new MaterialStack(Cerium, 1), new MaterialStack(Zirconium, 7), new MaterialStack(Rutile, 6), new MaterialStack(Niobium, 4), new MaterialStack(Oxygen, 10)), GENERATE_ORE);
+    public static final DustMaterial Zirkelite = new DustMaterial(904, "zirkelite", 0x6B5E6A, MaterialIconSet.DULL, 4, of(new MaterialStack(Calcium, 2), new MaterialStack(Thorium, 2), new MaterialStack(Cerium, 1), new MaterialStack(Zirconium, 7), new MaterialStack(Rutile, 6), new MaterialStack(Niobium, 4), new MaterialStack(Oxygen, 24)), GENERATE_ORE);
```
Comment (pablocnvs) [inline src/main/java/gregicadditions/GAMaterials.java:280]: Minor thing, this has to be 32 Oxygen if we go with every element at its highest oxidation state

File: src/main/java/gregicadditions/recipes/chain/BrineChain.java [hunk 2]
```diff
@@ -429,18 +429,19 @@ public static void init() {
                 .fluidOutputs(Oxygen.getFluid(6000))
                 .buildAndRegister();
 
-        // C6H6O2 + C3H6ClNS + 2H -> C6H6OS + (CH3)2NCH + HClO
+        // C6H6O2 + C3H6ClNS + Na -> C6H6OS + (CH3)2NCO + NaCl
         LARGE_CHEMICAL_RECIPES.recipeBuilder().duration(250).EUt(3200)
```
Comment (pablocnvs) [inline src/main/java/gregicadditions/recipes/chain/BrineChain.java:433]: I have just made a chain for that, if you want to consider adding.

**Review by pablocnvs — COMMENTED** [review]
Fine for me, the only thing is that for the dehydrogenation catalyst i made a small chain that you can check out and it should be a bit more accurate. In that sense mercaphenol needs to be changed to mercaptophenol.

Iridium Dehydrogenation Cataylst (2)

**Review by hjae78 — APPROVED** [review]

**Comment by hjae78** [comment]
Once Pcm's comments are addressed I'll merge this

File: src/main/java/gregicadditions/item/GAMetaItem.java [hunk 3]
```diff
@@ -306,7 +306,6 @@ public void registerSubItems() {
         DEGENERATE_RHENIUM_PLATE = addItem(430, "degenerate.rhenium.plate");
         DEGENERATE_RHENIUM_DUST = addItem(432, "degenerate.rhenium.dust");
         PLATE_FIELD_SHAPE = addItem(431, "plate.field.shape");
-        DUST_FIELD_SHAPE = addItem(439, "dust.field.shape");
```
Comment (TechLord22) [inline src/main/java/gregicadditions/item/GAMetaItem.java:309]: Commenting the free IDs will be useful for future reference.

File: src/main/java/gregicadditions/item/GAMetaItems.java [hunk 4]
```diff
@@ -542,5 +520,7 @@ public static void registerOreDict() {
         OreDictUnifier.registerOre(new ItemStack(Items.SNOWBALL), dust, Snow);
         OreDictUnifier.registerOre(new ItemStack(Blocks.SNOW), block, Snow);
         OreDictionary.registerOre("formWood", WOODEN_FORM_BRICK.getStackForm());
+        OreDictUnifier.registerOre(HOT_IRON_INGOT.getStackForm(), OrePrefix.ingotHot, Materials.Iron);
```
Comment (TechLord22) [inline src/main/java/gregicadditions/item/GAMetaItems.java:523]: We may want to avoid the oredict of `ingotHot` for this one. It doesn't have a freezer recipe, so it might break automation, and also really doesn't need an oredict as a result of EBF or Arc Furnace wrought iron creation.

**Review by TechLord22 — APPROVED** [review]

File: src/main/java/gregicadditions/item/GAMetaItem.java (hunk 3 above)
Comment (DStrand1) [reply src/main/java/gregicadditions/item/GAMetaItem.java:309]: Our IDs in this class are really sporadic, so perhaps this could be the subject of another reorganization PR

File: src/main/java/gregicadditions/recipes/chain/BrineChain.java (hunk 2 above)
Comment (DStrand1) [reply src/main/java/gregicadditions/recipes/chain/BrineChain.java:433]: I'm going to pull this commit out for now, and open an issue for your chain

**Comment by DStrand1** [comment]
The rebase was to drop the Dimethylformamide change, since we want to address this as a small chain instead, which I feel should be in a separate PR. So, all reviews are addressed
