### PR TITLE
More Recipe Fixes

### LINKED ISSUE #521: make the small gear craft a config
not everyone likes the GT5U way of doing small gears I think it should be a configurable thing such as the wrench craft changes.

### PR DESCRIPTION
**Pull request by DStrand1**
This PR addresses a few issues with recipes, some left over from past PRs, and others older issues:
- Add Assembler Recipes for Drums and Crates including Wood, as they require tools to craft
- Add crushed -> crushedPurified recipes to the Simple Ore Washer
- Fix Schematics decomposing to Stainless Steel, despite being crafted with Steel
- Add a config for harder manual Small Gear recipes instead of forcing it, supersedes #522
- Add 2 <material> -> 1 Small Gear to alloy smelter, for LV Small Gear automation
- Fix Dense Plates, Foils, Double Plates, and Curved Plates using improper recipe durations
- Add Direct Smelting to Iron for Basaltic and Granitic Mineral Sand
- Fix Red Slurry tooltip displaying Silicon despite not containing it
- Add Integrated Circuits to Soldering Alloy, Tin Alloy, and Battery Alloy
- Add Strontium Superconductor Dust en_us localization
- Add Nugget->Ingot and Ingot->Nugget Alloy Smelter Mold recipes
- Rework 1->9 and 3x3 Crafting Table removals, to more easily specify which to disable. As a result, the previous Packer, Unpacker, and Compressor Recipes will always be generated no matter the configs. Additionally, all of these removals are now set to default **false**
- Change Gear hand recipe to use a Wrench instead of a Screwdriver, since it has no screws in the recipe
- Increase the duration of Hot Ingot Vacuum Freezer recipes, to make the upcoming Cryogenic Freezer more viable. This isn't a super significant increase, and the Vacuum Freezer will still easily be faster than a single EBF
- Remove all Small and Tiny Dust Mixer and Crafting Table Alloy recipes since they are basically just JEI clutter. This was at the suggestion of @Shattered2909
- Add mechanism for automatically applying our configured Solder Fluids to Assembly Line and Circuit Assembler recipes. Brief documentation of how to use:
    - Recipes for each solder fluid will automatically be added to your provided recipe
    - You can set `solderMultiplier(int)` to increase the amount of solder used
    - If you call `noSolder()` on the builder, then solder fluids will not be applied even if there are no fluids in the recipe

The release containing this PR will once again need a config file regeneration, which should be noted on release.

Closes #521

### CODE REVIEW

**Comment by DStrand1** [comment]
Last commit moves Steel fluid extraction to LV, so that Small Steel Gears are still automatable at LV, for LV Electric Pistons.

**Review by ALongStringOfNumbers — APPROVED** [review]
Looks good to me. Do we also want to add assembler recipes for the wooden crates and wooden barrels to be consistent?

**Review by TechLord22 — APPROVED** [review]

**Comment by DStrand1** [comment]
PR opening comment is updated addressing all commits up to this point

File: src/main/java/gregicadditions/recipes/RecipeHandler.java [hunk 1]
```diff
@@ -973,28 +972,34 @@ private static void processSpringSmall(OrePrefix prefix, IngotMaterial material)
...
+     * + Lossy Small Gear recipe in Alloy Smelter (similar to normal Gears)
      *
      * - Removes Forge Hammer Recipe for Small Gears
      */
     private static void processGearSmall(OrePrefix prefix, IngotMaterial material) {
 
         if (material.hasFlag(GENERATE_SMALL_GEAR)) {
-            removeRecipeByName(String.format("gtadditions:small_gear_%s", material.toString()));
 
+            removeRecipeByName(String.format("gtadditions:small_gear_%s", material.toString()));
```
Comment (hjae78) [inline src/main/java/gregicadditions/recipes/RecipeHandler.java:985]: Why are we removing this recipe? Can't we just not add it in the first place?

**Review by hjae78 — APPROVED** [review]

**Review by TechLord22 — APPROVED** [review]

File: src/main/java/gregicadditions/recipes/RecipeHandler.java (hunk 1 above)
Comment (DStrand1) [reply src/main/java/gregicadditions/recipes/RecipeHandler.java:995]: Its complicated, but the naming of this recipe is a minor bug in Forge.

When we add Processing Handlers to GTCE OrePrefixes, *both* our and GTCE's handlers will have any and all Crafting Table recipes registered in them under the `gtadditions` namespace. Basically, GTCE registered that recipe but it got attributed to us.

**Comment by DStrand1** [comment]
Opening comment has once again been updated for the most recent 3 commits

**Review by TechLord22 — APPROVED** [review]
